In [38]:
from datasets import load_dataset
import pandas as pd

In [43]:
ds = load_dataset("cornell-movie-review-data/rotten_tomatoes", split=None)

# Your downloads will be faster (and you get access to private and requested datasets) if you add your HF token
# the below line works (adding it to the function) but is not recommended practice if you share code. see: https://huggingface.co/docs/hub/en/security-tokens#best-practices
# ds = load_dataset(dataset_name, token="your_token_here")

_load_dataset()_ will return a DatasetDict, usually something like:

```
DatasetDict({
    train: Dataset(...),
    test: Dataset(...)
}
```

In [ ]:
# if its a dict ... we can check out keys, hoorray!
ds.keys()

dict_keys(['train', 'validation', 'test'])

The dataset already comes split.
Each split is a separate object.

Conceptually:
- ds → container
- ds["train"] → actual dataset
- ds["train"][0] → one example

if we want it more "inspectable", we convert to a **pd** DataFrame

In [25]:
ds["train"].features

{'text': Value('string'), 'label': ClassLabel(names=['neg', 'pos'])}

In [11]:
# load "train"
df = ds["train"].to_pandas()
df.head()

                                                text  label
0  the rock is destined to be the 21st century's ...      1
1  the gorgeously elaborate continuation of " the...      1
2                     effective but too-tepid biopic      1
3  if you sometimes like to go to the movies to h...      1
4  emerges as something rare , an issue movie tha...      1

In [12]:
# how many of each label are there?
df['label'].value_counts()

label
1    4265
0    4265
Name: count, dtype: int64

In [13]:
# we loaded "train" split, but what about "test" split? 
df2 = ds["test"].to_pandas()
print(df2['label'].value_counts())
df2.head()

label
1    533
0    533
Name: count, dtype: int64

                                                text  label
0  lovingly photographed in the manner of a golde...      1
1              consistently clever and suspenseful .      1
2  it's like a " big chill " reunion of the baade...      1
3  the story gives ample opportunity for large-sc...      1
4                  red dragon " never cuts corners .      1

In [15]:
# there was also a "validation set"?
df3 = ds["validation"].to_pandas()
df3['label'].value_counts()

label
1    533
0    533
Name: count, dtype: int64

In [41]:
# How can we do this elegantly?
dfs = []

for key in ds.keys():
    print(key)
    tmp = ds[key].to_pandas()
    print("len of set:", len(tmp))
    dfs.append(tmp)

final = pd.concat(dfs)
print("final length:", len(final))
final.head()

train
len of set: 8530
validation
len of set: 1066
test
len of set: 1066
final length: 10662

                                                text  label
0  the rock is destined to be the 21st century's ...      1
1  the gorgeously elaborate continuation of " the...      1
2                     effective but too-tepid biopic      1
3  if you sometimes like to go to the movies to h...      1
4  emerges as something rare , an issue movie tha...      1

In [ ]:
# let's make everything a function

def load_and_concat(dataset_name):
    # loading the dataset with the name
    ds = load_dataset(dataset_name)
    # see what sets are in there
    print("Keys:", ds.keys())
    # print("Len of sets:", [len(ds[key]) for key in ds.keys()])
    # collect all sets to pandas dfs in a list
    dfs = [ds[key].to_pandas() for key in ds.keys()]
    # concatenate
    final = pd.concat(dfs)
    print("Final len:", len(final))
    # return the result
    return final

In [ ]:

df = load_and_concat("cornell-movie-review-data/rotten_tomatoes")
df.head()

### trying to .py this

- we'll just move back to slides for a sec to get function + py + terminal to work together